networks:
  backend:

services:
  postgres:
    image: postgres:16
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data
      - ${VOLUME_PATH}/backup:/backup
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - backend

  backup:
    build: .
    depends_on:
      - postgres
    volumes:
      - ${VOLUME_PATH}/backup:/backup
      # activate while developing
      - ./Scripts:/Scripts
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MAX_BACKUPS=1
      - INIT_BACKUP=1
      - CRON_TIME=0 0 * * *
    restart: unless-stopped
    networks:
      - backend

volumes:
  data:
