name: Publish Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test build "evoweb/postgres-cron-backup"

    steps:
      - uses: actions/checkout@v4

      - name: Test Bash scripts
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y devscripts shellcheck
          make test-scripts

      - name: Test image
        env:
          VOLUME_PATH: /tmp/postgres
          POSTGRES_DB: foo
          POSTGRES_USER: bar
          POSTGRES_PASSWORD: baz
        run: |
          docker compose up -d postgres
          docker compose run --rm backup /Scripts/backup.sh
          docker compose run --rm backup /Scripts/restore.sh /backup/latest.foo.sql.gz
          docker compose stop

  build:
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        version: [ 16, 17 ]

    runs-on: ubuntu-latest
    name: Build "evoweb/postgres-cron-backup:${{ matrix.version }}" and push it to repository
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: evoweb/postgres-cron-backup

      - name: Build for test
        id: build
        continue-on-error: true
        uses: docker/build-push-action@v6
        with:
          file: Versions/${{ matrix.version }}.x/Dockerfile
          context: .
          load: true
          tags: |
            evoweb/postgres-cron-backup:${{ matrix.version }}
            evoweb/postgres-cron-backup:${{ matrix.version }}.x
            evoweb/postgres-cron-backup:${{ matrix.version }}-${{ github.ref_name }}

      - name: Test the build image
        if: steps.build.outputs.imageid != ''
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/postgres-cron-backup:${{ matrix.version }} psql --version

      - name: Login to Docker Hub
        if: steps.build.outputs.imageid != '' && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build multi architecture image
        if: steps.build.outputs.imageid != '' && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/build-push-action@v6
        with:
          file: Versions/${{ matrix.version }}.x/Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' && github.ref_name != 'main' }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
          tags: |
            evoweb/postgres-cron-backup:${{ matrix.version }}
            evoweb/postgres-cron-backup:${{ matrix.version }}.x
            evoweb/postgres-cron-backup:${{ matrix.version }}-${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
